### ISSUE TITLE
No such file or directory: 'pico8'

### ISSUE THREAD

**Issue by felipebueno** [Neko250/sublime-PICO-8#1]
Hi, @Neko250 .

First of all, thank you for this project. There's a lot of Sublime Text users out there and I think it'll be very useful.

I'm not a Sublime Text so I don't know if I'm missing something. I installed ST3 here to test your package and followed your instructions for the OS X but I could't get it to work. It keeps saying ```[Errno 2] No such file or directory: 'pico8'```

Here's some screenshots:

<img width="1280" alt="screen shot 2016-06-28 at 16 42 04" src="https://cloud.githubusercontent.com/assets/241271/16430123/79ec4674-3d50-11e6-9dfd-651400d11d59.png">

<img width="1280" alt="screen shot 2016-06-28 at 16 41 58" src="https://cloud.githubusercontent.com/assets/241271/16430134/7d28a904-3d50-11e6-91d7-a1bb12bdeaae.png">

**Comment by Neko250** [comment]
I'm working on a different way to run cartridges: through a Python plugin. So you setup the PICO-8 path in the `.sublime-settings` and just run a command in the command palette.

**Comment by Neko250** [comment]
New Cartridge Runner implemented in version `2016.6.30` !

**Comment by felipebueno** [comment]
:+1:

**Comment by Neko250** [comment]
Sorry, coming in matter of minutes, version `2016.7.1`... can't run Python plugins from a compressed package: added `.no-sublime-package`.

**Comment by felipebueno** [comment]
Hi, @Neko250 

I upgraded the package and it woks now. I've just found two more bugs. I'm going to create new issues for them.

Thanks,

Felipe
