### ISSUE TITLE
auto indent not working as intended

### ISSUE THREAD

**Issue by stephantual** [Neko250/sublime-PICO-8#11]
type: "function whatever()"
type contents of function
press enter
type "end"
... end is indented.

Expected behaviour: end reindents back to match its opening function operator

This is true for edit > line > reindent which just basically ignores all indentation and flatlines everything to column 1.

**Comment by Neko250** [comment]
I think it's a Sublime Text issue. I've tested it on my machine.

1. Open Sublime Text, new document.
2. Command Palette: `Set Syntax: Lua`.
    - type: `function whatever()`.
    - type: `    -- contents`.
    - press enter
    - type: `end`
3. `end` is indented.

This process does not involve sublime-PICO-8 whatsoever. Yet it still happens... 😨

**Comment by stephantual** [comment]
Thanks @Neko250 -  just tried on v.3.0 3043 build and still no dice :(
