### ISSUE TITLE
osx - Cart only runs if the file contains a header

### ISSUE THREAD

**Issue by felipebueno** [Neko250/sublime-PICO-8#3]
I tried to describe the problems using only the screenshots. Please, let me know if you need more info.

**Hint:**
Read the PRINT statements 😄 

<img width="1280" alt="screen shot 2016-07-01 at 15 37 29" src="https://cloud.githubusercontent.com/assets/241271/16531465/fc1febd8-3fa2-11e6-9ed0-763e28938a06.png">
<img width="1278" alt="screen shot 2016-07-01 at 15 38 45" src="https://cloud.githubusercontent.com/assets/241271/16531464/fc070e38-3fa2-11e6-8cf5-99fc0569c166.png">
<img width="1280" alt="screen shot 2016-07-01 at 15 40 55" src="https://cloud.githubusercontent.com/assets/241271/16531463/fbf93d30-3fa2-11e6-9683-cf5985c1372f.png">
<img width="1280" alt="screen shot 2016-07-01 at 15 45 42" src="https://cloud.githubusercontent.com/assets/241271/16531462/fbe4cd1e-3fa2-11e6-8b9b-7670b80def81.png">

**Comment by felipebueno** [comment]
Hmm I thinks the last one (small fonts) is a PICO-8's problem. There's a thread about it on the BBS: http://www.lexaloffle.com/bbs/?tid=3217

**Comment by Neko250** [comment]
About the header issue: PICO-8 is intended to read `.p8` files, those files have a specific file format. This plugin does no add the missing cartridge parts, eg. `__gfx__`, `__gff__`, `__map__`... You should open a cartridge with that format (generated with PICO-8), or add those parts for yourself.

About the font: I'll add a listener to convert all the text inside the cartridge to lowercase upon saving it or something.
