### ISSUE TITLE
Uppercase letters.

### ISSUE THREAD

**Issue by s4e-tom** [Neko250/sublime-PICO-8#5]
Hello!

I used Sublimetext 3 and your Pico-8 plugin during GlobalGameJam 2017. It's a very nice plugin.

At one moment my game behaved strangely on code inspired by tutorials. Code that worked if I copy pasted it directly into my game. Strange!

After an hour spent slamming my head on my keyboard, I found the culprit: uppercase letters that look the exact same as lowercase later when using the plugin.

![uppercase](https://cloud.githubusercontent.com/assets/3964857/22264361/f24cb67c-e277-11e6-82de-b73d7daceef9.PNG)

Now I often CTRL-K CTRL-L my code to lowercase everything, but do you think anything could be done to prevent that? When coding directly in Pico-8, symbols are written instead of uppercase letter.

**Comment by Neko250** [comment]
Fixed !
